import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import Aside from "@/src/components/Aside";


export const metadata: Metadata = {
  title: "Next.js Project 2.0",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'], 
  display: 'swap'
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={poppins.className}>
      <body className="to-gray-900 from-gray-950 bg-gradient-to-t text-white">
        <Aside/>
        {children}
      </body>
    </html>
  );
}
